### ISSUE TITLE
Scripts page

### ISSUE THREAD

**Issue by mehul-m-prajapati** [tapasweni-pathak/tapasweni-pathak.github.io#4]
Hi,

There is no Scripts.html file in your repository - http://tapasweni-pathak.github.io/Scripts/

Can you tell me, where is this html file ?

**Comment by tapasweni-pathak** [comment]
I didn't get what you asked. Can you please be more clear? Why have you raised an issue on this repository?

**Comment by mehul-m-prajapati** [comment]
Hi Tapasweni,

I can access the page - http://tapasweni-pathak.github.io/Scripts/

Can you tell me, where is html file of this page located in your repo ?

**Comment by tapasweni-pathak** [comment]
Oh, okay. [Here](https://github.com/tapasweni-pathak/Scripts/tree/gh-pages) it is.
